---
- name: Run uninstall command
  win_command: '{{ uninstall_command }}'
  ignore_errors: true
  async: '{{ uninstall_timeout | int }}'
  poll: 5
  register: output

- name: Set uninstall output
  set_fact:
    output_uninstall: '{{ output }}'

- name: Cleanup registry exe
  include_tasks: registry_cleanup.yml
  vars:
    path_1: '{{ uninstall_path }}'
    path_2: '{{ software_path }}'
  when: type == 'exe'

- name: Cleanup registry msi
  include_tasks: registry_cleanup.yml
  vars:
    return_code: '{{ output_uninstall.rc }}'
  when: type == 'msi'
